[package]
name = "demo_34"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
demo_34_libs = { path = "../demo_34_libs" }
rand = "0.8.5"
